import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: 'transparent',
  },
  globalBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  stepShellBlur: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 540,
    borderRadius: 34,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  stepShellMobileBlur: {
    alignSelf: 'stretch',
    maxWidth: '100%',
    borderRadius: 0,
    borderWidth: 0,
    flexGrow: 1,
  },
  stepShell: {
    flexGrow: 1,
  },
  stepShellMobile: {
    flexGrow: 1,
  },
  heroPanel: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 34,
    alignItems: 'center',
    gap: 14,
  },
  heroTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroBackButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  heroBackButtonPressed: {
    opacity: 0.88,
  },
  heroSpacer: {
    width: 38,
  },
  heroStepLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1.2,
    color: '#38BDF8',
    textTransform: 'uppercase',
  },
  heroIconTile: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  heroTitle: {
    marginTop: 4,
    fontFamily: fontFamily.heading,
    fontSize: 24,
    lineHeight: 30,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  heroSubtitle: {
    fontFamily: fontFamily.body,
    fontSize: 14,
    lineHeight: 22,
    color: '#CBD5E1',
    textAlign: 'center',
    maxWidth: 320,
  },
  formPanel: {
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 26,
    gap: 16,
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  formPanelMobile: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  infoPanel: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoPanelText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#94A3B8',
  },
  inputLabel: {
    color: '#F8FAFC',
  },
  fieldHelper: {
    marginTop: -8,
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#94A3B8',
  },
  fieldHelperValid: {
    color: '#4ADE80',
  },
  ruleCard: {
    gap: 8,
    paddingHorizontal: 6,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ruleText: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    color: '#94A3B8',
  },
  ruleTextMet: {
    color: '#4ADE80',
  },
  pinGroup: {
    gap: 8,
  },
  mpinGroup: {
    gap: 8,
  },
  pinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#FFFFFF',
  },
  mpinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#FFFFFF',
  },
  pinRequired: {
    color: '#F87171',
  },
  mpinRequired: {
    color: '#F87171',
  },
  pinPressable: {
    width: '100%',
  },
  mpinPressable: {
    width: '100%',
  },
  pinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  mpinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  pinBox: {
    flex: 1,
    minHeight: 60,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mpinBox: {
    flex: 1,
    minHeight: 60,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pinBoxFilled: {
    borderColor: '#818CF8',
    backgroundColor: 'rgba(129,140,248,0.15)',
  },
  pinBoxFocused: {
    borderColor: '#6366F1',
    backgroundColor: 'rgba(99,102,241,0.2)',
  },
  mpinBoxFocused: {
    borderColor: '#6366F1',
    backgroundColor: 'rgba(99,102,241,0.2)',
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#818CF8',
  },
  mpinDigit: {
    fontFamily: fontFamily.heading,
    fontSize: 24,
    color: '#818CF8',
  },
  hiddenKeyboardInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  mpinInputWrap: {
    width: '100%',
    position: 'relative',
  },
  mpinOverlayInput: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.02,
    color: 'transparent',
    backgroundColor: 'transparent',
  },
  policyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  policyToggle: {
    paddingTop: 3,
  },
  policyText: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 21,
    color: '#E2E8F0',
  },
  policyLink: {
    color: '#818CF8',
    fontFamily: fontFamily.bodySemi,
  },
  checkboxRow: {
    minHeight: 62,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
  },
  checkboxRowActive: {
    borderColor: '#818CF8',
    backgroundColor: 'rgba(129,140,248,0.15)',
  },
  checkboxRowPressed: {
    opacity: 0.94,
  },
  checkboxBox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#94A3B8',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBoxActive: {
    borderColor: '#818CF8',
    backgroundColor: '#818CF8',
  },
  checkboxLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 14,
    lineHeight: 22,
    color: '#F8FAFC',
  },
  checkboxRowWrapper: {
    marginTop: 8,
    marginBottom: 8,
  },
  checkboxLabelLarge: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 15,
    color: '#F8FAFC',
    marginBottom: 2,
  },
  checkboxSubtext: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#94A3B8',
  },
  termsTable: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    overflow: 'hidden',
    marginBottom: 24,
  },
  termsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  termsRowHeader: {
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  termsRowLast: {
    borderBottomWidth: 0,
  },
  termsCellFeature: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#CBD5E1',
  },
  termsCellFeatureHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#F8FAFC',
  },
  termsCellDetails: {
    flex: 1,
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
    color: '#F8FAFC',
  },
  termsCellDetailsHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#F8FAFC',
  },
  termsText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#94A3B8',
    marginBottom: 24,
  },
  activationCard: {
    borderRadius: 22,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 10,
  },
  activationBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(74, 222, 128, 0.2)',
    borderWidth: 1,
    borderColor: '#4ADE80',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activationTitle: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 20,
    color: '#F8FAFC',
    textAlign: 'center',
  },
  activationText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#94A3B8',
    textAlign: 'center',
  },
  docChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  docChipLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#E2E8F0',
  },
  docChipStatus: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
  },
  retryBtn: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#F87171',
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
    backgroundColor: 'rgba(248, 113, 113, 0.1)',
  },
  retryBtnText: {
    color: '#F87171',
    fontFamily: fontFamily.bodyBold,
    fontSize: 14,
  },
  summaryCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryLabel: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#94A3B8',
  },
  summaryValue: {
    flex: 1,
    textAlign: 'right',
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#F8FAFC',
  },
  inlineNote: {
    textAlign: 'center',
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#64748B',
  },
  inlineNoteActive: {
    color: '#4ADE80',
  },
  inlineNoteMuted: {
    color: '#64748B',
  },
  primaryAction: {
    marginTop: 6,
  },
  primaryActionDisabled: {
    opacity: 0.5,
  },
  progressRail: {
    height: 5,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#818CF8',
  },
  fallbackText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#94A3B8',
  },
  imageUploadBtn: {
    height: 120,
    width: '100%',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.2)',
    borderStyle: 'dashed',
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  imageUploadPreview: {
    width: '100%',
    height: '100%',
  },
  imageUploadPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  imageUploadText: {
    color: '#818CF8',
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
  },
});
