import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, radius, shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: '#080D1A',
  },
  globalBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  stepShellBlur: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 540,
    borderRadius: 34,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    ...shadows.card,
  },
  stepShellMobileBlur: {
    alignSelf: 'stretch',
    maxWidth: '100%',
    borderRadius: 0,
    borderWidth: 0,
    flexGrow: 1,
  },
  stepShell: {
    flexGrow: 1,
  },
  stepShellMobile: {
    flexGrow: 1,
  },
  heroPanel: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 30,
    alignItems: 'center',
    gap: 14,
  },
  heroTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
  },
  heroBackButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.96 }],
  },
  heroSpacer: {
    width: 40,
  },
  heroStepLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1.5,
    color: colors.cyan,
    textTransform: 'uppercase',
  },
  heroIconTile: {
    width: 62,
    height: 62,
    borderRadius: 20,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    borderWidth: 1.5,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    ...shadows.glow,
  },
  heroTitle: {
    marginTop: 4,
    fontFamily: fontFamily.heading,
    fontSize: 24,
    lineHeight: 30,
    color: '#FFFFFF',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  heroSubtitle: {
    fontFamily: fontFamily.body,
    fontSize: 13.5,
    lineHeight: 21,
    color: colors.textSecondary,
    textAlign: 'center',
    maxWidth: 320,
  },
  formPanel: {
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 26,
    gap: 16,
    backgroundColor: '#080D1A',
  },
  formPanelMobile: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  infoPanel: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.25)',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoPanelText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  inputLabel: {
    color: '#E2E8F0',
  },
  fieldHelper: {
    marginTop: -8,
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  fieldHelperValid: {
    color: colors.successLight,
  },
  ruleCard: {
    gap: 8,
    paddingHorizontal: 6,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ruleText: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    color: colors.textSecondary,
  },
  ruleTextMet: {
    color: colors.successLight,
  },
  pinGroup: {
    gap: 8,
  },
  mpinGroup: {
    gap: 8,
  },
  pinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#E2E8F0',
  },
  mpinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#E2E8F0',
  },
  pinRequired: {
    color: colors.cyan,
  },
  mpinRequired: {
    color: colors.cyan,
  },
  pinPressable: {
    width: '100%',
  },
  mpinPressable: {
    width: '100%',
  },
  pinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  mpinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  pinBox: {
    flex: 1,
    minHeight: 60,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.glass,
  },
  mpinBox: {
    flex: 1,
    minHeight: 60,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.glass,
  },
  pinBoxFilled: {
    borderColor: 'rgba(56, 189, 248, 0.45)',
    backgroundColor: '#131F37',
  },
  pinBoxFocused: {
    borderColor: colors.cyan,
    backgroundColor: '#1E293B',
    borderWidth: 2,
    ...shadows.glow,
  },
  mpinBoxFocused: {
    borderColor: colors.cyan,
    backgroundColor: '#1E293B',
    borderWidth: 2,
    ...shadows.glow,
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.cyan,
  },
  mpinDigit: {
    fontFamily: fontFamily.heading,
    fontSize: 24,
    color: '#FFFFFF',
  },
  hiddenKeyboardInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  mpinInputWrap: {
    width: '100%',
    position: 'relative',
  },
  mpinOverlayInput: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.02,
    color: 'transparent',
    backgroundColor: 'transparent',
  },
  policyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  policyToggle: {
    paddingTop: 3,
  },
  policyText: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 21,
    color: '#E2E8F0',
  },
  policyLink: {
    color: colors.cyan,
    fontFamily: fontFamily.bodySemi,
  },
  checkboxRow: {
    minHeight: 58,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
  },
  checkboxRowActive: {
    borderColor: 'rgba(56, 189, 248, 0.45)',
    backgroundColor: '#131F37',
  },
  checkboxRowPressed: {
    opacity: 0.9,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBoxActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  checkboxLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 14,
    lineHeight: 22,
    color: '#FFFFFF',
  },
  checkboxRowWrapper: {
    marginTop: 8,
    marginBottom: 8,
  },
  checkboxLabelLarge: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 15,
    color: '#FFFFFF',
    marginBottom: 2,
  },
  checkboxSubtext: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  termsTable: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    overflow: 'hidden',
    marginBottom: 20,
  },
  termsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  termsRowHeader: {
    backgroundColor: 'rgba(37, 99, 235, 0.15)',
  },
  termsRowLast: {
    borderBottomWidth: 0,
  },
  termsCellFeature: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: colors.textSecondary,
  },
  termsCellFeatureHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#FFFFFF',
  },
  termsCellDetails: {
    flex: 1,
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
    color: '#FFFFFF',
  },
  termsCellDetailsHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#FFFFFF',
  },
  termsText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
    marginBottom: 20,
  },
  activationCard: {
    borderRadius: radius.lg,
    backgroundColor: '#0F172A',
    borderWidth: 1,
    borderColor: 'rgba(52, 211, 153, 0.35)',
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 10,
    ...shadows.glass,
  },
  activationBadge: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(16, 185, 129, 0.18)',
    borderWidth: 1.5,
    borderColor: colors.successLight,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.profit,
  },
  activationTitle: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 20,
    color: '#FFFFFF',
    textAlign: 'center',
  },
  activationText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  docChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  docChipLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#E2E8F0',
  },
  docChipStatus: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
  },
  retryBtn: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.dangerLight,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
  },
  retryBtnText: {
    color: colors.dangerLight,
    fontFamily: fontFamily.bodyBold,
    fontSize: 14,
  },
  summaryCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    backgroundColor: '#0F172A',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    ...shadows.glass,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryLabel: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: colors.textSecondary,
  },
  summaryValue: {
    flex: 1,
    textAlign: 'right',
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#FFFFFF',
  },
  inlineNote: {
    textAlign: 'center',
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: colors.muted,
  },
  inlineNoteActive: {
    color: colors.successLight,
  },
  inlineNoteMuted: {
    color: colors.muted,
  },
  primaryAction: {
    marginTop: 6,
  },
  primaryActionDisabled: {
    opacity: 0.45,
  },
  progressRail: {
    height: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.cyan,
  },
  fallbackText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: colors.textSecondary,
  },
  imageUploadBtn: {
    height: 124,
    width: '100%',
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: 'rgba(56, 189, 248, 0.35)',
    borderStyle: 'dashed',
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: '#0F172A',
  },
  imageUploadPreview: {
    width: '100%',
    height: '100%',
  },
  imageUploadPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  imageUploadText: {
    color: colors.cyan,
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
  },
});
