import { Platform, StyleSheet } from 'react-native';
import { colors, fontFamily, radius, shadows } from '../../constants/theme';

export const styles = StyleSheet.create({
  page: {
    flexGrow: 1,
    backgroundColor: '#F7F8FA',
  },
  globalBackground: {
    ...StyleSheet.absoluteFillObject,
  },
  stepShellBlur: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 540,
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    ...shadows.card,
  },
  stepShellMobileBlur: {
    alignSelf: 'stretch',
    maxWidth: '100%',
    borderRadius: 0,
    borderWidth: 0,
    flexGrow: 1,
  },
  stepShell: {
    flexGrow: 1,
  },
  stepShellMobile: {
    flexGrow: 1,
  },
  heroPanel: {
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 28,
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  heroTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  heroBackButtonPressed: {
    opacity: 0.85,
    transform: [{ scale: 0.96 }],
  },
  heroSpacer: {
    width: 40,
  },
  heroStepLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
    letterSpacing: 1,
    color: '#6B7280',
    textTransform: 'uppercase',
  },
  heroIconTile: {
    width: 60,
    height: 60,
    borderRadius: 18,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  heroTitle: {
    marginTop: 4,
    fontFamily: fontFamily.heading,
    fontSize: 22,
    lineHeight: 28,
    color: '#111827',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  heroSubtitle: {
    fontFamily: fontFamily.body,
    fontSize: 13.5,
    lineHeight: 21,
    color: '#6B7280',
    textAlign: 'center',
    maxWidth: 320,
  },
  formPanel: {
    paddingHorizontal: 22,
    paddingTop: 20,
    paddingBottom: 26,
    gap: 16,
    backgroundColor: '#F7F8FA',
  },
  formPanelMobile: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  infoPanel: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#DBEAFE',
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoPanelText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#1E40AF',
  },
  inputLabel: {
    color: '#374151',
  },
  fieldHelper: {
    marginTop: -8,
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#6B7280',
  },
  fieldHelperValid: {
    color: '#16A34A',
  },
  ruleCard: {
    gap: 8,
    paddingHorizontal: 6,
  },
  ruleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ruleText: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    color: '#6B7280',
  },
  ruleTextMet: {
    color: '#16A34A',
  },
  pinGroup: {
    gap: 8,
  },
  mpinGroup: {
    gap: 8,
  },
  pinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#374151',
  },
  mpinLabel: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#374151',
  },
  pinRequired: {
    color: '#2563EB',
  },
  mpinRequired: {
    color: '#2563EB',
  },
  pinPressable: {
    width: '100%',
  },
  mpinPressable: {
    width: '100%',
  },
  pinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  mpinRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  pinBox: {
    flex: 1,
    minHeight: 58,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.soft,
  },
  mpinBox: {
    flex: 1,
    minHeight: 58,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.soft,
  },
  pinBoxFilled: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  pinBoxFocused: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
    borderWidth: 2,
  },
  mpinBoxFocused: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
    borderWidth: 2,
  },
  pinDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#2563EB',
  },
  mpinDigit: {
    fontFamily: fontFamily.heading,
    fontSize: 24,
    color: '#111827',
  },
  hiddenKeyboardInput: {
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  mpinInputWrap: {
    width: '100%',
    position: 'relative',
  },
  mpinOverlayInput: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.02,
    color: 'transparent',
    backgroundColor: 'transparent',
  },
  policyRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  policyToggle: {
    paddingTop: 3,
  },
  policyText: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 21,
    color: '#4B5563',
  },
  policyLink: {
    color: '#2563EB',
    fontFamily: fontFamily.bodySemi,
  },
  checkboxRow: {
    minHeight: 56,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 14,
  },
  checkboxRowActive: {
    borderColor: '#DBEAFE',
    backgroundColor: '#EFF6FF',
  },
  checkboxRowPressed: {
    opacity: 0.9,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBoxActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  checkboxLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 14,
    lineHeight: 22,
    color: '#374151',
  },
  checkboxRowWrapper: {
    marginTop: 8,
    marginBottom: 8,
  },
  checkboxLabelLarge: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 15,
    color: '#111827',
    marginBottom: 2,
  },
  checkboxSubtext: {
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#6B7280',
  },
  termsTable: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    marginBottom: 20,
  },
  termsRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    paddingVertical: 14,
    paddingHorizontal: 16,
  },
  termsRowHeader: {
    backgroundColor: '#EFF6FF',
  },
  termsRowLast: {
    borderBottomWidth: 0,
  },
  termsCellFeature: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#6B7280',
  },
  termsCellFeatureHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#111827',
  },
  termsCellDetails: {
    flex: 1,
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
    color: '#111827',
  },
  termsCellDetailsHeader: {
    flex: 1,
    fontFamily: fontFamily.headingSemi,
    fontSize: 13,
    color: '#111827',
  },
  termsText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#6B7280',
    marginBottom: 20,
  },
  activationCard: {
    borderRadius: radius.lg,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#BBF7D0',
    paddingHorizontal: 18,
    paddingVertical: 20,
    alignItems: 'center',
    gap: 10,
    ...shadows.card,
  },
  activationBadge: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#DCFCE7',
    borderWidth: 1.5,
    borderColor: '#16A34A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activationTitle: {
    fontFamily: fontFamily.headingSemi,
    fontSize: 20,
    color: '#111827',
    textAlign: 'center',
  },
  activationText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#6B7280',
    textAlign: 'center',
  },
  docChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  docChipLabel: {
    flex: 1,
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#374151',
  },
  docChipStatus: {
    fontFamily: fontFamily.bodyBold,
    fontSize: 12,
  },
  retryBtn: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 4,
    backgroundColor: '#FEF2F2',
  },
  retryBtnText: {
    color: '#DC2626',
    fontFamily: fontFamily.bodyBold,
    fontSize: 14,
  },
  summaryCard: {
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 10,
    ...shadows.card,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryLabel: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    color: '#6B7280',
  },
  summaryValue: {
    flex: 1,
    textAlign: 'right',
    fontFamily: fontFamily.bodyBold,
    fontSize: 13,
    color: '#111827',
  },
  inlineNote: {
    textAlign: 'center',
    fontFamily: fontFamily.body,
    fontSize: 12,
    lineHeight: 18,
    color: '#9CA3AF',
  },
  inlineNoteActive: {
    color: '#16A34A',
  },
  inlineNoteMuted: {
    color: '#9CA3AF',
  },
  primaryAction: {
    marginTop: 6,
  },
  primaryActionDisabled: {
    opacity: 0.45,
  },
  progressRail: {
    height: 4,
    backgroundColor: '#E5E7EB',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#2563EB',
  },
  fallbackText: {
    fontFamily: fontFamily.body,
    fontSize: 13,
    lineHeight: 20,
    color: '#6B7280',
  },
  imageUploadBtn: {
    height: 124,
    width: '100%',
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: '#DBEAFE',
    borderStyle: 'dashed',
    overflow: 'hidden',
    marginTop: 4,
    marginBottom: 8,
    backgroundColor: '#F8FAFC',
  },
  imageUploadPreview: {
    width: '100%',
    height: '100%',
  },
  imageUploadPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  imageUploadText: {
    color: '#2563EB',
    fontFamily: fontFamily.bodySemi,
    fontSize: 13,
  },
});
